name: Build and Test Ironuki

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js 20.11.0
        uses: actions/setup-node@v3
        with:
          node-version: "20.11.0"

      - name: Install dependencies on macOS
        if: runner.os == 'macOS'
        run: |
          brew install python@3.9
          sudo xcode-select --install || echo "Command Line Tools already installed"

      - name: Install dependencies on Windows
        if: runner.os == 'Windows'
        run: choco install python visualstudio2022-workload-vctools -y

      - name: Download and install KB2919442 and KB2919355
        if: runner.os == 'Windows'
        run: |
          Invoke-WebRequest -Uri "https://download.microsoft.com/download/2/4/4/244eae22-1a60-4b93-b3aa-1071d467f1c1/Windows8.1-KB2919442-x64.msu" -OutFile "C:\kb2919442.msu"
          Invoke-WebRequest -Uri "https://download.microsoft.com/download/2/4/4/244eae22-1a60-4b93-b3aa-1071d467f1c1/Windows8.1-KB2919355-x64.msu" -OutFile "C:\kb2919355.msu"
          wusa.exe C:\kb2919442.msu /quiet /norestart
          wusa.exe C:\kb2919355.msu /quiet /norestart

      - name: Install Node.js dependencies
        run: npm install

      - name: Run npx ironuki
        run: npx ironuki

      - name: Build and test npx command
        run: echo "Building and testing on ${{ matrix.os }} complete"
