name: Build and Test Ironuki

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js 20.11.0
        uses: actions/setup-node@v3
        with:
          node-version: "20.11.0"

      - name: Install dependencies on macOS
        if: runner.os == 'macOS'
        run: |
          brew install python@3.9
          sudo xcode-select --install || echo "Command Line Tools already installed"

      - name: Install dependencies on Windows
        if: runner.os == 'Windows'
        run: |
          choco install python visualstudio2022-workload-vctools -y
          npm config set python python3

      - name: Install Node.js dependencies
        run: npm install

      - name: Run npx ironuki
        run: npx ironuki

      - name: Build and test npx command
        run: |
          npm test
          echo "Building and testing on ${{ matrix.os }} complete"
